kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: blob-storage-class
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blob-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blob-storage-class
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-storage-deployment
  labels:
    app: blob-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-storage
  template:
    metadata:
      labels:
        app: blob-storage
    spec:
      containers:
        - name: blob-storage
          image: docker.io/kfcmanager/blobstore:1.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volv
              mountPath: /data
      volumes:
        - name: volv
          persistentVolumeClaim:
          claimName: blob-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: blob-storage-service
spec:
  selector:
    app: blob-storage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
