apiVersion: v1
kind: Namespace
metadata:
  name: image-dataset

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-storage-class
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: image-dataset
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storage-class
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: image-dataset
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      namespace: image-dataset
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/pgvector/pgvector:0.8.0-pg16
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: volv
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              value: wert1234
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: postgres-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: image-dataset
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: image-dataset
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      namespace: image-dataset
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: docker.io/arm64v8/rabbitmq:4.0.4
          ports:
            - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: image-dataset
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
  type: ClusterIP

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: blob-storage-class
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blob-volume-claim
  namespace: image-dataset
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blob-storage-class
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api-deployment
  namespace: image-dataset
  labels:
    app: data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      namespace: image-dataset
      labels:
        app: data-api
    spec:
      containers:
        - name: data-api
          image: docker.io/kfcmanager/data-api:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volv
              mountPath: /data
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "wert1234"
            - name: BUCKET_PATH
              value: "./data"
            - name: QUEUE_HOST
              value: "rabbitmq-service"
            - name: QUEUE_PORT
              value: "5672"
            - name: QUEUE_NAME
              value: "embedding"
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: blob-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: data-api-service
  namespace: image-dataset
spec:
  selector:
    app: data-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip-deployment
  namespace: image-dataset
  labels:
    app: clip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clip
  template:
    metadata:
      namespace: image-dataset
      labels:
        app: clip
    spec:
      containers:
        - name: clip
          image: docker.io/kfcmanager/clip:1.0.0
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "wert1234"
            - name: API_HOST
              value: "data-api-service"
            - name: QUEUE_HOST
              value: "rabbitmq-service"
            - name: QUEUE_PORT
              value: "5672"
            - name: QUEUE_NAME
              value: "embedding"
