apiVersion: v1
kind: Namespace
metadata:
  name: image-dataset

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-storage-class
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"

---
apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "postgres-cluster"
  namespace: "image-dataset"
spec:
  teamId: "image-dataset"
  volume:
    size: "100Gi"
    storageClass: "postgres-storage-class"
  numberOfInstances: 3
  users:
    postgres:
      - "superuser"
      - "createdb"
  databases:
    postgres: postgres
  postgresql:
    version: "16"
  patroni:
    synchronous_mode: true
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
