apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: rook-ceph
      repoURL: https://github.com/rook/rook.git
      targetRevision: v1.15.5
      path: deploy/examples
      directory:
        include:
          - crds.yaml
          - common.yaml
          - operator.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
