---
- name: Initialize master node
  hosts: master
  become: yes
  tasks:
    - name: Create cluster
      shell: |
        kubeadm config images pull &&
        kubeadm init

    - name: Initialize kube config
      shell: |
        mkdir -p $HOME/.kube &&
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config &&
        chown $(id -u):$(id -g) $HOME/.kube/config &&

    - name: Install Calico CNI plugin
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.0/manifests/calico.yaml
      become: no

    - name: Install ArgoCD
      shell: |
        kubectl create namespace argocd &&
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml &&
        kubectl port-forward -n argocd svc/argocd-server 8080:443
      become: no
